### ISSUE TITLE
Feature request: position as arguments in the url

### ISSUE THREAD

**Issue by fdov21** [owlmaps/uacontrolmap-timelines#1]
Something like https://owlmaps.github.io/uacontrolmap-timelines/positions/ {lat},<lon},{zoom}
Open the page at this position and zoom-level.

**Comment by foosint** [comment]
I just looked through the code, its actually not that hard to implement.
All parameters as normal query params: ?param1=value&param2=value&....
I also have an idea for an button to easy generate the url from the current settings. Will refactor/reorganize the current code and implement these feature soon.

**Comment by foosint** [comment]
Feature implemented, playback controls, custom url parameter with url generation (somewhat obscured)
