### ISSUE TITLE
Feature request: from, to, speed as arguments in the url.

### ISSUE THREAD

**Issue by fdov21** [owlmaps/uacontrolmap-timelines#2]
This builds on #1 
Something like https://owlmaps.github.io/uacontrolmap-timelines/positions/ {lat},<lon},{zoom}?from=010123?to=010223?speed=3

Would make it possible to tailor URLs to show specific events.

**Comment by foosint** [comment]
Feature implemented, playback controls, custom url parameter with url generation (somewhat obscured)
